<?php

return [
    [
        "name" => "Soldat",
        "slug" => "soldier",
        "type" => "base",
        "desc" => "Combattant par excellence, le soldat est un expert dans l'utilisation d'armes de toutes sortes.",
        "basePV" => 10,
        "baseForce" => null,
        "featsFrequency" => "1 par niveau",
        "skillsModifier" => 2,
        "powersModifier" => "",
        "baseBBA" => 1,
        "baseToughness" => 2,
        "baseReflexes" => 0,
        "baseWill" => 0
    ],
    [
        "name" => "Éclaireur",
        "slug" => "scout",
        "type" => "base",
        "desc" => "Un explorateur qui ne se sent vraiment chez lui qu'en bordure de l'espace connu.",
        "basePV" => 8,
        "baseForce" => null,
        "featsFrequency" => "1 par niveau sauf aux niveaux 4, 10 et 16 où il n'en gagne aucun.",
        "skillsModifier" => 3,
        "powersModifier" => "",
        "baseBBA" => 0,
        "baseToughness" => 2,
        "baseReflexes" => 2,
        "baseWill" => 2
    ],
    [
        "name" => "Voyou",
        "slug" => "scoundrel",
        "type" => "base",
        "desc" => "Un roublard faisant principalement appel à son astuce et à son sens de la discrétion.",
        "basePV" => 6,
        "baseForce" => null,
        "featsFrequency" => "1 par niveau sauf aux niveaux 4, 10, 16 et 19 où il n'en gagne aucun.",
        "skillsModifier" => 4,
        "powersModifier" => "",
        "baseBBA" => 0,
        "baseToughness" => 0,
        "baseReflexes" => 2,
        "baseWill" => 0
    ],
    [
        "name" => "Combattant de la Force",
        "slug" => "forceFighter",
        "type" => "forceUser",
        "desc" => "Des utilisateurs de la Force qui favorisent le combat au contact. Ils sont connus sous le nom de Jedi Gardiens et de Guerriers Sith.",
        "basePV" => 10,
        "baseForce" => 4,
        "featsFrequency" => "1 par niveau sauf aux niveaux 4, 10 et 16 où il n'en gagne aucun.",
        "skillsModifier" => 1,
        "powersModifier" => "2 au niveau 1 puis 1 par niveau suivant.",
        "baseBBA" => 1,
        "baseToughness" => 2,
        "baseReflexes" => 2,
        "baseWill" => 1
    ],
    [
        "name" => "Chevalier de la Force",
        "slug" => "forceKnight",
        "type" => "forceUser",
        "desc" => "Des utilisateurs de la Force qui conservent un bon équilibre entre le combat au contact et les pouvoirs de la Force. Il sont connus sous le nom de Sentinelles Jedi et de Maraudeurs Sith.",
        "basePV" => 8,
        "baseForce" => 6,
        "featsFrequency" => "1 par niveau sauf aux niveaux 4, 10, 16 et 19 où il n'en gagne aucun.",
        "skillsModifier" => 2,
        "powersModifier" => "2 au niveau 1 puis 1 par niveau suivant.",
        "baseBBA" => 0,
        "baseToughness" => 2,
        "baseReflexes" => 2,
        "baseWill" => 2
    ],
    [
        "name" => "Sorcier de la Force",
        "slug" => "forceSorcerer",
        "type" => "forceUser",
        "desc" => "Des utilisateurs de la Force particulièrement érudits, qui privilégient l'utilisation de pouvoirs liés à la Force à toute autre forme de combat. Ils sont connus sous le nom de Jedi Consulaires et d'Inquisiteurs Sith.",
        "basePV" => 6,
        "baseForce" => 8,
        "featsFrequency" => "1 par niveau sauf aux niveaux 3, 6, 10, 16 et 19 où il n'en gagne aucun.",
        "skillsModifier" => 3,
        "powersModifier" => "2 au niveau 1 puis 1 par niveau suivant sauf aux niveaux 5, 9, 13 et 17 où il en gagne 2.",
        "baseBBA" => 0,
        "baseToughness" => 2,
        "baseReflexes" => 1,
        "baseWill" => 2
    ]
];
